version: "3.9"
services:
  hub:
    build: .
    ports:
      - "1234:1234"
    environment:
      - OAUTH2_CLIENT_ID=
      - OAUTH2_CLIENT_SECRET=
      - OAUTH2_REDIRECT_URI=http://127.0.0.1:1234/discord/callback
      - GUILD_ID=
      - ROLE_ID=
      - SPAM_TOKEN=
      - DISCORD_WEBHOOK_URL=
    volumes:
      - db:/db/
      - ./wireguard:/wireguard
volumes:
  db:
